version: '3'

services:
    backend:
        build:
            context: .
            dockerfile: ./backend.dockerfile
        image: backend
        container_name: backend
        environment:
            - PYTHONUNBUFFERED=TRUE
        ports:
            - "3000:5000"

    frontend:
        build:
            context: .
            dockerfile: ./frontend.dockerfile
        image: frontend
        container_name: frontend
        ports:
            - "80:8080"
            # - "80:3000"
        depends_on:
            - 'backend'
